### ISSUE TITLE
Strong naming

### ISSUE THREAD

**Issue by springy76** [StephenCleary/AsyncEx.Coordination#11]
Is it on intention or just lazyness that the assemblies or not strong named? Binding redirects are handled automatically with newer VS versions.

**Comment by springy76** [comment]
I just noticed you reference Nivot.StrongNaming in the other AsyncEx variant (will will really maintain both of them??):

This will a) not work on for an automatic build server b) I'm allergic to PowerShell.

**Comment by StephenCleary** [comment]
It's by intention. Strong naming causes a *lot* of problems - just Google it. I'll consider public ("open-source") signing when it's supported by the tooling.

There's no CI build (yet) for the old Nito.AsyncEx, and you don't have to use PowerShell.
