### ISSUE TITLE
AsyncManualResetEvent

### ISSUE THREAD

**Issue by hannasm** [StephenCleary/AsyncEx.Coordination#15]
I'm trying  to use your (brilliant) library but something strange is happening:

        [TestMethod]
        public void TestMethod1()
        {
            AsyncManualResetEvent a1 = new AsyncManualResetEvent();

            var t = Task.Run(async () =>
            {
                await Task.Delay(100);
                a1.Set();
                return 123;
            }).ContinueWith(t2 =>
            {
                Debug.WriteLine("Cancelled");
            }, TaskContinuationOptions.OnlyOnCanceled);

            a1.WaitAsync().Wait();

            t.Wait();

            Debug.WriteLine("done");
        }

Of course, if you run this, you will see, 

        Test Name:	TestMethod1
        Test FullName:	NitoAsyncManualResetEventError.UnitTest1.TestMethod1
        Test Source:	J:\Projects\ListenerDotNet\NitoAsyncManualResetEventError\UnitTest1.cs : line 14
        Test Outcome:	Failed
        Test Duration:	0:00:00.1272536

        Result StackTrace:	
        at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken         cancellationToken)
           at System.Threading.Tasks.Task.Wait()
           at NitoAsyncManualResetEventError.UnitTest1.TestMethod1() in         J:\Projects\ListenerDotNet\NitoAsyncManualResetEventError\UnitTest1.cs:line 29
        Result Message:	
        Test method NitoAsyncManualResetEventError.UnitTest1.TestMethod1 threw exception: 
        System.AggregateException: One or more errors occurred. --->         System.Threading.Tasks.TaskCanceledException: A task was canceled.
        
I'm pretty sure this is a bug and not me doing something stupid, but i haven't been able to track it down yet. 

Thanks

**Comment by hannasm** [comment]
Well i guess the task continuation that is set to 'OnlyOnCancelled' gets cancelled when my task isn't canelled, so what i really want was to continue my continuation with a task that ignores the cancellation.


        [TestMethod]
        public void Test007()
        {
            AsyncManualResetEvent a1 = new AsyncManualResetEvent();

            var t = Task.Run(async () =>
            {
                await Task.Delay(100);
                a1.Set();
                return 123;
            });

            var t2 = t.ContinueWith(t3 =>
            {
                Debug.WriteLine("Cancelled");
            }, TaskContinuationOptions.OnlyOnCanceled).ContinueWith(t4 =>
            {
                // do nothing
            }, TaskContinuationOptions.OnlyOnCanceled);

            var result = t.Result;

            t2.Wait();

            Debug.WriteLine("done");
        }

**Comment by StephenCleary** [comment]
Task continuations are tricky, and [`ContinueWith` has some unsafe default settings](http://blog.stephencleary.com/2013/10/continuewith-is-dangerous-too.html). You should use `await` instead of `ContinueWith`.
