### ISSUE TITLE
AsyncAutoResetEvent doesn't contain reset method

### ISSUE THREAD

**Issue by niemyjski** [StephenCleary/AsyncEx.Coordination#16]
`Like other "events", an AsyncManualResetEvent is either set or unset at any time. An AsyncManualResetEvent can be changed from unset to set by calling its Set method, and it can be changed from set to unset by calling its Reset method.`

**Comment by StephenCleary** [comment]
`AsyncAutoResetEvent` doesn't have a `Reset` method. `AsyncManualResetEvent` does.

Using `Reset` on an auto-reset event would be extremely odd, and probably is an indication that a different synchronization primitive would be a better fit. What's your use case?

**Comment by niemyjski** [comment]
Ahh, should have read the docs closer. I changed up the queue to use an autoresetevent because due to the usage we no longer have to get the counts for a semaphore etc.. But I'm noticing one case where it's set before I come into the wait and I know there is nothing there.
