### ISSUE TITLE
Easier-to-find Synchronous Attempt Functionality

### ISSUE THREAD

**Issue by StephenCleary** [StephenCleary/AsyncEx.Coordination#2]
The current AsyncEx library uses [a pattern](http://blog.stephencleary.com/2013/04/cancellationtoken-behavior-with-asyncex.html) where the end-user can pass an already-cancelled `CancellationToken` into any API to achieve a "synchronous attempt".

The main advantage of this approach is that it keeps the APIs quite clean.

The main disadvantages of this approach are that it's not very discoverable and that it can encourage using exceptions for control flow.

This issue is a brainstorming of alternatives.

Whatever solution we adopt will need to be consistent across these APIs:

    AsyncAutoResetEvent:
      Task WaitAsync(CancellationToken cancellationToken);
    AsyncConditionVariable:
      Task WaitAsync(CancellationToken cancellationToken);
    AsyncLock:
      AwaitableDisposable<IDisposable> LockAsync(CancellationToken cancellationToken);
    AsyncManualResetEvent:
      Task WaitAsync(CancellationToken cancellationToken);
    AsyncMonitor:
      AwaitableDisposable<IDisposable> EnterAsync(CancellationToken cancellationToken);
      Task WaitAsync(CancellationToken cancellationToken);
    AsyncSemaphore:
      Task WaitAsync(CancellationToken cancellationToken);
    PauseToken:
      Task WaitWhilePausedAsync(CancellationToken token);

as well as these prospective APIs (not currently in this project but will almost certainly be added):

    AsyncReaderWriterLock:
      AwaitableDisposable<IDisposable> ReaderLockAsync(CancellationToken cancellationToken);
      AwaitableDisposable<IDisposable> WriterLockAsync(CancellationToken cancellationToken);
    AsyncProducerConsumerQueue<T>:
      Task<T> DequeueAsync(CancellationToken cancellationToken);
      Task<DequeueResult> TryDequeueAsync(CancellationToken cancellationToken);
      Task EnqueueAsync(T item, CancellationToken cancellationToken);
      Task<bool> TryEnqueueAsync(T item, CancellationToken cancellationToken);
      Task<bool> OutputAvailableAsync(CancellationToken cancellationToken);

(`AwaitableDisposable<IDisposable>` is practically the same as `Task<IDisposable>` for the purpose of this conversation).

Note that the existing `Try*` members on `AsyncProducerConsumerQueue<T>` [are not like `TryLock` (synchronous attempt); rather, they are like `TryParse` (do not throw on error)](https://github.com/StephenCleary/AsyncEx/issues/17). These are going to be renamed.

Suggestions should have method declarations and usage examples for each of these:

    void Wait();
    IDisposable Lock();
    DequeueResult Dequeue();
    bool OutputAvailable();

@roend83 @IanYates @engdata

**Comment by StephenCleary** [comment]
The traditional `Try` approach uses `out` params:

    bool TryWait();
    bool TryLock(out IDisposable);
    bool TryDeque(out DequeResult);
    bool TryOutputAvailable(out bool);

One thing I particularly dislike about this approach is that `TryLock` has no way to call it safely:

    IDisposable key;
    if (mutex.TryLock(out key))
    {
      // Exception may be thrown here, causing a lock that will never be freed.
      using (key)
      {
        ...
      }
    }

Another dislike is because `TryOutputAvailable` has two boolean return values,

**Comment by StephenCleary** [comment]
Because of these problems (with the `TryLock` example), `Monitor.TryEnter` was [updated to be safer](https://msdn.microsoft.com/en-us/library/dd289679(v=vs.110).aspx) (with the `ref bool lockTaken` parameter), but the usage is quite poor and it isn't clear how to do the same with `IDisposable`.

However, we *can* have the returned `IDisposable` be `null`, which gives us the first real contender:

    bool TryWait();
    IDisposable TryLock(); // Return null on failure to lock
    DequeResult? TryDeque();
    bool? TryOuputAvailable();

Usage:

    if (signal.TryWait())
      ;

    using (var key = mutex.TryLock())
    {
      if (key == null)
        ;
    }

    var result = queue.TryDeque();
    if (result != null)
      ;

    var more = queue.TryOutputAvailable();
    if (more == null)
      ; // No more right now, might be more later.
    else if (!more.Value)
      ; // No more ever.

I'm not too wild about the nullable boolean, and I'm not particularly pleased with the `bool` return type for `TryWait` when all the other method styles use nullable return types.

**Comment by IanYates** [comment]
Interesting ideas.  I'm at a customer's site at the moment so don't have a lot of time for thoughts :)   (checking email in between a bit of downtime).

Could we have a returned class or struct that contains a status indicator as well as being disposable?  That way you could safely call it with a using statement - since you could always dispose - and check within that using to see if you actually got the lock and can proceed.  If you didn't get the lock then the disposal is effectively a no-op.

I'll think about it some more this evening.  I do like the idea of avoiding exception-based flow control and making it clear about whether we're trying to enter with no waiting versus being happy to wait for a definite (via timespan or cancellation token) or indefinite period.

**Comment by engdata** [comment]
The only knock I have against a null IDisposable being used as the success/failure marker is that `using((IDisposable)null){..}` is perfectly valid, and enters the inner scope. This makes it harder to intuit correct usage over an explicit bool.

I actually don't mind the syntax for AsyncMonitor.TryEnter / AsyncLock.TryLock with an out bool:

```
bool acquiredLock;

using(Monitor.TryEnter(out acquiredLock)
if(acquiredLock)
{
    ...
}
```
Returning a null IDisposable if not acquired. 
While I don't typically like the style, omitting the outer braces gives a 'single-looking' block (too bad we didn't get in-line out params in C# 6).

@IanYates suggestion for a disposable class with a success marker is also completely fair, but possibly slightly less idiomatic.

For the `TryOutputAvailable` method, I would be inclined to separate out the completion checking into a separate member such as `IsComplete`, and simply return a boolean for the `TryOutputAvailable`.

**Comment by StephenCleary** [comment]
Good ideas so far!

@engdata I don't think a boolean getter would work, unless I'm missing something; that operation must distinguish somehow between "none available right now" and "none available forevermore".

**Comment by engdata** [comment]
My thought was just having something like:
```
if (queue.IsCompleted)
   ; // No more ever. 
else if (queue.TryOutputAvailable())
   ; // No more right now, might be more later.
```
to split up the two concerns - but maybe I am missing something in the fundamentals. The boolean getter could potentially just be replaced with / a light wrapper around the completion task's IsCompleted member (thinking of the dataflow blocks as an example, though they do not have Try / synchronous members).

**Comment by sjbsjb** [comment]
Instead of returning an IDisposable, how about returning a type that implements IDisposable and which also defines an implicit conversion to the type that we want it to have, such as bool. The using clause will treat it as an IDisposable, so that the cleanup is done, but then in the body of the using clause you can use it as the desired type.

struct LockReturn : IDisposable {
...
public static implicit operator bool( LockReturn Lr) {...}
...
}

using (var locked = x.TryLock()) {
 if (locked) {...}
}

- sjb

**Comment by StephenCleary** [comment]
I'll need to make a decision on this soon. Paging @niemyjski, if you'd like to chime in.

**Comment by IanYates** [comment]
I like @sjb-sjb 's idea, probably because it's similar to mine but more elegant whilst still being pretty discoverable (although maybe because I've just read this thread I'm not necessarily a good judge of discoverability).

However it does't really meet all of the criteria...  It's 12:15am here so I'll literally sleep on it and see if I can make a meaningful suggestion tomorrow.

I'm keen to give the new library a go but will need to do something about reader/writer locks as I use them extensively.

**Comment by niemyjski** [comment]
I'm all for passing in a cancellation token. I wish it was there today but there are some questions that need to be addressed.

* I think they all need to be optional: `CancellationToken token = default(CancellationToken)`
* What do you do if you pass in a cancelled token? In some places in our queues we pass in a cancelled token to say we want to see if we can dequeue some work and if we can't bail immediately (so we are still doing some work).
* I think it would be nice to have some extension methods that accept a TimeSpan and convert that to a cancellation token.. That's what we are doing today.

What ever direction we go, I feel like it needs to be consistent across the board.

**Comment by niemyjski** [comment]
In the case of TryLock, would that not throw an error but return null if the cancellation token becomes cancelled? What if the cancellation token is cancelled does it immediately return null?

**Comment by StephenCleary** [comment]
I'm also leaning towards @sjb-sjb's proposal, though we do have to flesh it out and make sure it still makes sense when applied consistently.

Consistency is my highest priority in this. The functionality is all there today, it's just not very discoverable. Worst case scenario is it will just stay that way. I'd rather have a somewhat odd but consistent solution rather than inconsistencies.

**Comment by StephenCleary** [comment]
@IanYates I have had RWL requests through private channels. It is definitely being put in, probably at lunch (in 2 hours for me). However, it will *not* have the notion of "upgradeable reader locks", only "reader locks" and "writer locks". Is that sufficient for your needs?

**Comment by StephenCleary** [comment]
@niemyjski:

> I think they all need to be optional: CancellationToken token = default(CancellationToken)

All the CTs are optional. Actually implemented by overloads and not default parameters, due to versioning/upgrade concerns.

> What do you do if you pass in a cancelled token? In some places in our queues we pass in a cancelled token to say we want to see if we can dequeue some work and if we can't bail immediately (so we are still doing some work).

That is the current semantics. *If* we can get a "TryDequeue" that is consistent with other "Try" behaviors, then I *might* revisit the current semantics so that CTs are always honored. It will be consistent one way or the other, though; either CTs will always be ignored on success (current behavior), or CTs will always be honored first. I have a question out to @stephentoub about his thoughts on this.

> I think it would be nice to have some extension methods that accept a TimeSpan and convert that to a cancellation token.. That's what we are doing today.

I'll consider that.

Most "timeout" APIs in the BCL only exist because they're more efficient than wrapping a TimeSpan in a CancellationTokenSource, and then doing the operation with a generic CancellationToken (which often requires registering a manual cancel callback). Most Win32 APIs for timeouts can just take a timeout value directly instead of that roundabout way, avoiding plenty of allocations.

In the case of async coordination primitives, everything's in our code to begin with, so there isn't any implementation benefit of taking a timespan. The implementations would literally just be wrapping the timespan in a CT and passing it along. It could be seen as an end-user benefit, though.

**Comment by niemyjski** [comment]
We did new CancellationTokenSource(timeout).Token overloads because we wanted to keep everything clean and consistent. Yes, there are more allocations but it saves from having a ton of overloads :).

**Comment by StephenCleary** [comment]
@IanYates ARWL is in version `1.0.0-delta-4`.

**Comment by StephenCleary** [comment]
Fleshed out the "Try types with implicit bool conversion" approach. It's on the `TryTypes` branch; example usage is [here](https://github.com/StephenCleary/AsyncEx.Coordination/blob/e9361bc2ccd00bdabe5ac85f8bdf42101f2da0b5/test/UnitTests/TryExampleUsage.cs).

**Comment by IanYates** [comment]
@StephenCleary - wow - thanks.  I had no expectation for you to do it (particularly over your lunch hour).  I don't use the upgrade locks so am super happy with just readers and writers.

I injured my leg yesterday (long and not interesting story) so that's going to keep me away from work for a couple of days whilst I get xrays, etc sorted but I'll see if I can sneak in the new AsyncEx at some stage towards the end of the week and exercise the code.  I build against .NET 4.6.1, and will jump to 4.6.2 as soon as it's out to avoid that issue where continuations don't run where they're supposed to.

**Comment by StephenCleary** [comment]
@IanYates I always do open-source work on my own time. It nicely avoids any questions over who owns the code. :)

I did decide to target AsyncEx.Tasks to `netstandard1.3` (net46), because that's the *API surface* that it needs. It's unfortunate that there's a bug in net46/net461, but I chose not to move the target to `netstandard1.5` just because of a desktop framework bug. The bug *is* rare - IIRC, it would only trigger if you use a synchronization primitive task (i.e., the result of `AsyncLock.LockAsync()`) in a `Task.WhenAll`/`Task.WhenAny`, and even if you do, it would work fine in *most* cases (it does, however, have a potential for deadlock in obscure situations).

**Comment by StephenCleary** [comment]
I've decided for now not to proceed with easier-to-find Synchronous Attempt functionality. However, this exercise did illustrate the difficulty with other `Try*` methods such as `TryDequeueAsync`. As a result of the experiments on the `TryTypes` branch, all `Try*` APIs have been removed. This will make it easier to add Synchronous Attempt APIs if we reconsider this in the future.
