### ISSUE TITLE
add net standard support

### ISSUE THREAD

**Issue by niemyjski** [StephenCleary/AsyncEx.Coordination#3]
I can't use the package until I use an import's statement for `netcore5.0` which I'd rather not do.

**Comment by niemyjski** [comment]
Also, is there any reason for supporting net46? Would net451 work?

**Comment by StephenCleary** [comment]
Ah, no, sorry.

The synchronization primitives are actually all using a replacement core implementation (`AsyncWaitQueue` and friends, which most people aren't even aware exists). The new core depends heavily on the `TaskCreationOptions.RunContinuationsAsynchronously` flag, [which was introduced in .NET 4.6](http://blogs.msdn.com/b/pfxteam/archive/2015/02/02/new-task-apis-in-net-4-6.aspx). This is necessary to prevent [thread pool starvation](https://github.com/StephenCleary/AsyncEx/issues/48) and [stack dives](https://github.com/StephenCleary/AsyncEx/issues/36), which can happen with the old implementation.

**Comment by StephenCleary** [comment]
In fact, the dependency will be on net462. Once it's released...

**Comment by niemyjski** [comment]
Thanks for the heads up!

**Comment by StephenCleary** [comment]
[1.0.0-beta-2](https://www.nuget.org/packages/Nito.AsyncEx.Coordination/1.0.0-beta-2) supports netstandard1.3 with proper (trimmed) dependencies.

Upon review, the bug that exists in 4.6's support for `RunContinuationsAsynchronously` is IMO rare enough that AsyncEx.Coordination will officially take a dependency on net46 / netstandard1.3.

**Comment by niemyjski** [comment]
Awesome! Just a heads up the rtm bits and tooling leaked. Check Twitter :)

Get Outlook for iOS




On Sat, Jun 25, 2016 at 9:55 PM -0500, "Stephen Cleary" <notifications@github.com> wrote:












1.0.0-beta-2 supports netstandard1.3 with proper (trimmed) dependencies.



Upon review, the bug that exists in 4.6's support for RunContinuationsAsynchronously is IMO rare enough that AsyncEx.Coordination will officially take a dependency on net46 / netstandard1.3.

**Comment by StephenCleary** [comment]
That is extremely unfortunate.

Also, I apparently don't follow the right people on Twitter for leaked software. :)

**Comment by niemyjski** [comment]
https://twitter.com/h0x0d and me of course (https://twitter.com/blaken)

**Comment by niemyjski** [comment]
I believe all the changes you need to make to support rtm is update tooling version in global.json and update dependencies :)

**Comment by StephenCleary** [comment]
Probably. Then further changes when the tooling RTMs.
