### ISSUE TITLE
Please provide a .net 4.6 framework target

### ISSUE THREAD

**Issue by niemyjski** [StephenCleary/AsyncEx.Coordination#5]
Right now all of your packages specify only a netstandard target... This is great but when you target the full framework you have to also bring in dependencies that already exist in the full framework:

https://www.nuget.org/packages/Nito.AsyncEx.Coordination

![screen shot 2016-07-05 at 3 26 04 pm](https://cloud.githubusercontent.com/assets/1020579/16598717/d616acea-42c4-11e6-92df-36ddee84155f.png)

The solution is to define a new full framework target and add build time dependencies: https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/project.json#L282-L292 for types that already exist.

**Comment by StephenCleary** [comment]
Done.

[`1.0.0-delta-7`](https://www.nuget.org/packages/Nito.AsyncEx.Coordination/1.0.0-delta-7) (and its dependencies) support full framework targets without bringing in .NET Core dependencies.
