### ISSUE TITLE
Waiting to require lock after WaitAsync cancelization

### ISSUE THREAD

**Issue by ThadHouse** [StephenCleary/AsyncEx.Coordination#7]
I have a project that is using `WaitAsync(token).Wait(TimeSpan timeout)` to build a wait with a timeout in my library synchronously. In doing so, my program is encountering an occasional deadlock. The deadlock happens when the async wait call gets canceled and my code leaves the scope of the using block that originally grabbed the lock. After this, the async call that was canceled finally returns, and reacquires the lock, which causes future code to deadlock trying to acquire the lock. I can prove this is the case as if I manually invoke a delay between cancelling the call, and leaving the using scope, this deadlock doesn't happen. 

Below is a minimal example of how to reproduce the issue, however it only works on slow systems. The faster the system, the less likely the race is to happen. 

Is there a way to assert that the lock is grabbed before leaving the using scope? Also note that this did not happen with the old AsyncEx library, and is exclusive to the new library.

```
using System;
using System.Threading;
using System.Threading.Tasks;
using Nito.AsyncEx;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            AsyncMonitor monitor = new AsyncMonitor();

            CancellationTokenSource source = new CancellationTokenSource();
            using(var disposable = monitor.Enter())
            {
                var task = monitor.WaitAsync(source.Token);
                bool success = task.Wait(TimeSpan.FromSeconds(1));
                source.Cancel();
                // Adding a forced delay here solves the issue
            }

            System.Threading.Thread.Sleep(1000);

             // Code will deadlock here
            monitor.Enter();
        }
    }
}
```

**Comment by StephenCleary** [comment]
The problem is that the code is leaving the `using` scope before the `WaitAsync` task is completed. For monitors, a "wait" must be done only while the monitor is entered; entering the monitor, *starting* a wait, and then leaving the monitor before that wait completes is incorrect usage.

This usage is correct (and does not deadlock):

    using(var disposable = monitor.Enter())
    {
        var task = monitor.WaitAsync(source.Token);
        bool success = task.Wait(TimeSpan.FromSeconds(1));
        source.Cancel();
        task.WaitWithoutException();
    }

If you do this kind of usage often, you might want to wrap it into an extension method.

**Comment by StephenCleary** [comment]
(BTW, the reason the old AsyncEx library happened to work is because it used synchronous continuations for its tasks, so the task would actually be completed by the time `Cancel` returned).

**Comment by ThadHouse** [comment]
Ah. I figured I had to call another wait, but just calling task.Wait() would throw an exception, and I didn't know the second Wait() call would complete with the thrown exception.. I only use it twice in my code, so its a pretty easy fix without needing an extension method. Thanks!
