### ISSUE TITLE
Add support for .NET Standard 1.0 

### ISSUE THREAD

**Issue by ravensorb** [StephenCleary/AsyncEx.Coordination#9]
There are a number of things in your excellent library that would work in .NET Standard 1.0 (ex: AwaitableDisposable).  It would be very useful if those were separated out into an assembly that can be installed in that profile.

**Comment by StephenCleary** [comment]
I've reviewed the type compatibility, and I believe the *only* types compatible with 1.0 would be `AwaitableDisposable` and `IdManager`.

Since these types both have limited usage outside this library and are both very small, I have concluded that splitting up this library is not the best choice.

If you disagree, please do present your reasons why 1.0 support would be helpful.

**Comment by ravensorb** [comment]
AwaitableDisposable and the various interfaces are they ones I was thinking about.  I happen to maintain a number of different frameworks and try hard to have them Target .NET Standard 1.0 -- your AwaitableDisposable and IAsyncWaitQueue have really come in handy in a number of apps I have written and having those available to a larger "surface area" of components would be great.  

Another option might be to setup Interfaces for all of you core classes and then expose them in a .NET Standard 1.0 package -- this would be my actual preference :) as then I could leverage thinks like the Manual Reset Event or the LazyLock from anywhere

**Comment by StephenCleary** [comment]
How interesting that you use `IAsyncWaitQueue` - I was not aware of anyone else using that. :) I assume you're already aware that the interface has changed with these new netcore libraries.

I could add some *interfaces* which would be `netstandard1.0`, but I won't write those implementations - they're just too hard to get right at that level of BCL. The only implementation of `IAsyncWaitQueue` I'm willing to support requires `netstandard1.3`.
